services:
  - type: web
    name: turn2law-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: turn2law_waitlist
      - key: DB_USER
        value: turn2law_user
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: turn2law-db
    databaseName: turn2law_waitlist
    user: turn2law_user
    region: singapore