# Generated by Django 4.2 on 2025-06-29 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("location", models.CharField(db_index=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("individual", "Individual needing legal help"),
                            ("business_owner", "Business Owner/Manager"),
                            ("lawyer", "Lawyer/Legal Professional"),
                            ("law_student", "Law Student"),
                            ("investor", "Investor/Partner"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("interests", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="waitlistentry",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
